GET http://localhost:5003/api

### register a new user
POST http://localhost:5003/api/register
Content-Type: application/json

### verify user - only first time
POST http://localhost:5003/api/verify
Content-Type: application/json

{
    "userId": "24d63534-2ffb-464a-8f3a-f169755ffad2",
    "token": "703171"
}

### validate otp for known user
POST http://localhost:5003/api/validate
Content-Type: application/json

{
    "userId": "1ae8eac8-82c2-4b18-890d-4c89331c0ca8",
    "token": "217416"
}